### ISSUE TITLE
Viewname file naming conventions for i18n {View}.{lang}.cshtml

### ISSUE THREAD

**Issue by Bartmax** [DamianEdwards/i18nStarterWeb#2]
Not always the best solution is to have resources for all values, sometimes modifying the whole html is more maintainable and easy. Specially for partial views.

It would be great if it can support something like the Home.mobile.cshtml behavior.

That way I can have Home.cshtml and Home.fr.cshtml 

I think this is particularly usefull for partial views and small websites or pages.

The usual terms and conditions content could be a great candidate for this too.

**Comment by DamianEdwards** [comment]
We have that support planned (although not committed to for v1) using the view expanders feature. There's a sample already at https://github.com/aspnet/Mvc/blob/dev/samples/MvcSample.Web/LanguageViewLocationExpander.cs
