### ISSUE TITLE
Data Annotations

### ISSUE THREAD

**Issue by Bartmax** [DamianEdwards/i18nStarterWeb#3]
Is there any plan for data annotations as well ?
Since we are using conventions for views, i was think of something like 

namespace something {
    public class SomeClass {
        [Required]
        public string Email {get;set;}
    }
}

looks at {namespace}.{someclass}.{lang}.resx
so I can have something.SomeClass.fr.resx with a key Email.Required

that would be the same as :

```
namespace something {
    public class SomeClass {
        [Required(LocString("SomeClass.Email.Required")]
        public string Email {get;set;}
    }
}
```

**Comment by DamianEdwards** [comment]
Yes, we have plans to support localizing strings from both model metadata annotations (e.g. `[DisplayName]` and any `ValidationAttribute`). See https://github.com/DamianEdwards/i18nStarterWeb/blob/master/src/Microsoft.AspNet.Mvc.Localization/ValidationAttributeLocalizerOfT.cs
