### ISSUE TITLE
Instructions need to be updated

### ISSUE THREAD

**Issue by glen-84** [DamianEdwards/i18nStarterWeb#6]
Step 3 (kvm upgrade dev) does not work, you need to do:

```
kvm upgrade
kvm alias default 1.0.0-beta3
kvm alias dev 1.0.0-beta4-11169
```

**Comment by DamianEdwards** [comment]
Can you check what KVM version you have? That ability was added recently

**Comment by glen-84** [comment]
K Version Manager - Build 10321

**Comment by DamianEdwards** [comment]
That's way old. Can you update it and try again. It should look like this:

![image](https://cloud.githubusercontent.com/assets/249088/6492696/4a3dad26-c26a-11e4-97c6-02ef60407fc7.png)

**Comment by glen-84** [comment]
You refer to: https://github.com/aspnet/Home#optimistic

Which says to use: `@powershell -NoProfile -ExecutionPolicy unrestricted -Command "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/master/kvminstall.ps1'))}"`

Which downloads: https://raw.githubusercontent.com/aspnet/Home/dev/kvm.ps1

Which is build #10321

What am I doing wrong? :worried:

**Comment by DamianEdwards** [comment]
Ah I think that's an issue on our end. It seems our bot isn't pushing the latest KVM bits to the home repo properly. I'm trying to get it fixed.

In the meantime you can just grab the latest bits directly from https://github.com/aspnet/dotnetsdk/tree/dev/src

**Comment by DamianEdwards** [comment]
This should be fixed now, thanks for the report!

**Comment by glen-84** [comment]
Thanks Damian. :+1:
